CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status SMALLINT,
   name VARCHAR(255) NOT NULL,
   phone_number BIGINT NOT NULL,
   email_address VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_emailaddress UNIQUE (email_address);

ALTER TABLE users ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);