CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status SMALLINT,
   name VARCHAR(255) NOT NULL,
   phone_number BIGINT NOT NULL,
   email_address VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user" ADD CONSTRAINT uc_user_emailaddress UNIQUE (email_address);

ALTER TABLE "user" ADD CONSTRAINT uc_user_phonenumber UNIQUE (phone_number);