CREATE TABLE comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status SMALLINT,
   user_name VARCHAR(255) NOT NULL,
   text VARCHAR(255) NOT NULL,
   created_at date,
   updated_at date,
   art_id BIGINT,
   user_id BIGINT,
   CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment ADD CONSTRAINT FK_COMMENT_ON_ART FOREIGN KEY (art_id) REFERENCES art (id);

ALTER TABLE comment ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);